services:

    api:
      build:
        context: .
        dockerfile: Dockerfile
      expose:
        - 8000
      environment:
        - DB__HOST=db
        - REDIS__HOST=redis
      env_file:
       - ".env"
      restart: unless-stopped
      volumes:
        - ./keys:/app/keys
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy

    db:
      image: postgres:18-alpine
      ports:
        - '5432:5432'
      volumes:
        - postgres_data:/var/lib/postgresql
      environment:
        - POSTGRES_DB=${DB__NAME}
        - POSTGRES_USER=${DB__USER}
        - POSTGRES_PASSWORD=${DB__PASSWORD}
      restart: unless-stopped
      healthcheck:
        test: ["CMD-SHELL", "pg_isready -U ${DB__USER} -d ${DB__NAME}"]
        interval: 5s
        timeout: 10s
        retries: 3

    redis:
      image: redis:alpine
      ports:
        - '6379:6379'
      restart: unless-stopped
      volumes:
        - redis_data:/data
      healthcheck:
        test: ["CMD", "redis-cli", "ping"]
        interval: 5s
        timeout: 10s
        retries: 3

    celery_worker:
      build: .
      command: celery -A src.app.core.celery worker --loglevel=info
      environment:
        - DB__HOST=db
        - REDIS__HOST=redis
      env_file:
        - ".env"
      restart: unless-stopped
      volumes:
        - ./keys:/app/keys:ro
      depends_on:
        db:
          condition: service_healthy
        redis:
          condition: service_healthy

    celery_beat:
      build: .
      command: celery -A src.app.core.celery beat --loglevel=info
      environment:
        - DB__HOST=db
        - REDIS__HOST=redis
      env_file:
        - ".env"
      restart: unless-stopped
      volumes:
        - ./keys:/app/keys:ro
      depends_on:
        celery_worker:
          condition: service_started

volumes:
  postgres_data:
  redis_data: