events {
    worker_connections 1024;
}

http {
    server_tokens off;
    include /etc/nginx/mime.types;

    server {
        listen 80;
        server_name localhost;


        location / {
                proxy_pass http://api:8000/docs;
                proxy_set_header Host $Host;
                proxy_set_header X-Real-IP $remote_addr;
            }

        location /openapi.json {
            proxy_pass http://api:8000/openapi.json;
                proxy_set_header Host $Host;
                proxy_set_header X-Real-IP $remote_addr;
        }

    }
}