"""feat added is_superadmin to user

Revision ID: 300e77898bfe
Revises: 2946711369c5
Create Date: 2026-06-27 12:19:23.173899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '300e77898bfe'
down_revision: Union[str, Sequence[str], None] = '2946711369c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_superadmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_superadmin')
    # ### end Alembic commands ###
