"""perf(export logs: user_id and created_at indexes

Revision ID: 38adda305266
Revises: 99ea09cc8cdc
Create Date: 2026-07-29 21:26:21.608594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '38adda305266'
down_revision: Union[str, Sequence[str], None] = '99ea09cc8cdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_export_logs_created_at'), 'export_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_export_logs_user_id'), 'export_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_export_logs_user_id'), table_name='export_logs')
    op.drop_index(op.f('ix_export_logs_created_at'), table_name='export_logs')
    # ### end Alembic commands ###
