"""refactor: timestampt mixins

Revision ID: 72c597f8e8c7
Revises: 38adda305266
Create Date: 2026-08-04 19:59:44.168689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '72c597f8e8c7'
down_revision: Union[str, Sequence[str], None] = '38adda305266'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clicks', 'created_at')
    op.add_column('short_urls', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.create_index(op.f('ix_short_urls_created_at'), 'short_urls', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_short_urls_created_at'), table_name='short_urls')
    op.drop_column('short_urls', 'updated_at')
    op.add_column('clicks', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
