"""delete: click model

Revision ID: 8570b67e7919
Revises: e30fbd5df8c5
Create Date: 2026-08-14 17:50:54.666553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8570b67e7919'
down_revision: Union[str, Sequence[str], None] = 'e30fbd5df8c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clicks_url_created'), table_name='clicks')
    op.drop_table('clicks')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clicks',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('url_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('user_ip', sa.VARCHAR(length=45), autoincrement=False, nullable=False),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['url_id'], ['short_urls.id'], name=op.f('clicks_url_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('clicks_pkey'))
    )
    op.create_index(op.f('ix_clicks_url_created'), 'clicks', ['url_id', 'created_at'], unique=False)
    # ### end Alembic commands ###
