"""feat: return created_at to Click model

Revision ID: e30fbd5df8c5
Revises: 72c597f8e8c7
Create Date: 2026-08-05 20:23:55.405481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e30fbd5df8c5'
down_revision: Union[str, Sequence[str], None] = '72c597f8e8c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clicks', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_index(op.f('ix_clicks_url_id'), table_name='clicks')
    op.create_index('ix_clicks_url_created', 'clicks', ['url_id', 'created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clicks_url_created', table_name='clicks')
    op.create_index(op.f('ix_clicks_url_id'), 'clicks', ['url_id'], unique=False)
    op.drop_column('clicks', 'created_at')
    # ### end Alembic commands ###
